#include "gaudi/test/test.hpp"
#include "gaudi/test/view_tests.hpp"
#include "gaudi/test/simplex_algorithm_tests.hpp"
#include "gaudi/test/morton_simplex_tests.hpp"
#include "gaudi/test/bvh_tests.hpp"
#include "gaudi/test/pyramid_datum_tests.hpp"
#include "gaudi/test/calder_winding_tests.hpp"
#include "gaudi/test/darboux_cyclide_tests.hpp"
#include "gaudi/calder/shell_area_conservation_test.hpp"
#include "gaudi/calder/rod_length_conservation_test.hpp"
#include "gaudi/test/rod_dynamic_tests.hpp"
#include "gaudi/test/shell_dynamic_tests.hpp"
#include "gaudi/test/tree_backend_validation_tests.hpp"
#include "gaudi/test/field_tests.hpp"
#include "gaudi/test/field_graph_tests.hpp"
#include "gaudi/test/medial_graph_tests.hpp"
#include "gaudi/test/cyclide_smooth_tests.hpp"
#include "gaudi/test/kusama_cyclide_smooth_tests.hpp"
#include "gaudi/test/medial_bench_tests.hpp"
#include "gaudi/test/solver_node_tests.hpp"
#include "gaudi/test/rod_solver_tests.hpp"
#include "gaudi/test/rod_force_graph_tests.hpp"
#include "gaudi/test/rod_mesh_snapshot_tests.hpp"
#include "gaudi/test/dipole_tunneling_tests.hpp"
#include "liblombardi_tests.cpp"

int main() {
  auto result = gaudi::test::Registry::run_all();
  return result.failed == 0 ? 0 : 1;
}
