"""Emit C++ in albers style (Q[i], x_v, vec3, mat3, 2.0 literals)."""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence, Tuple

import sympy as sp
from sympy import Matrix, Symbol

from eigen_printer import (
    EigenCodegenConfig,
    EigenPrinter,
    emit_vec3_function,
)


def _banner() -> str:
    return (
        "// AUTO-GENERATED by scripts/sympy/generate.py — do not edit\n"
        "#pragma once\n\n"
        "#include <cmath>\n"
        "#include \"gaudi/common.h\"\n"
        "#include <Eigen/Dense>\n\n"
        "namespace gaudi {\nnamespace albers {\nnamespace medial_generated {\n\n"
    )


def _footer() -> str:
    return "\n} // namespace medial_generated\n} // namespace albers\n} // namespace gaudi\n"


class AlbersPrinter(EigenPrinter):
    """Map sympy symbols to albers naming conventions."""

    def __init__(self, symbol_map: Optional[Dict[Symbol, str]] = None, **kwargs):
        super().__init__(symbol_map=symbol_map, config=EigenCodegenConfig(), **kwargs)

    def _print_Symbol(self, expr: Symbol) -> str:
        if expr in self._symbol_map:
            return self._symbol_map[expr]
        name = str(expr)
        if name.startswith("Q") and name[1:].isdigit():
            return f"Q[{name[1:]}]"
        if name.startswith("C") and name[1:].isdigit():
            return f"Q[{name[1:]}]"
        return super()._print_Symbol(expr)


def _quadric_symbol_map() -> Dict[Symbol, str]:
    from quadric import Q

    m: Dict[Symbol, str] = {}
    for i, s in enumerate(Q):
        m[s] = f"Q[{i}]"
    from implicit import x, y, z

    m[x] = "x[0]"
    m[y] = "x[1]"
    m[z] = "x[2]"
    return m


def _darboux_symbol_map() -> Dict[Symbol, str]:
    from darboux import A, B, Cc, Dc, E, F, G, H, I, J, kap, lam, mu, nu

    m: Dict[Symbol, str] = {
        A: "A",
        B: "B",
        Cc: "C",
        Dc: "D",
        E: "E",
        F: "F",
        G: "G",
        H: "H",
        I: "I",
        J: "J",
        lam: "lambda",
        mu: "mu",
        nu: "nu",
        kap: "kappa",
    }
    from implicit import x, y, z

    m[x] = "x"
    m[y] = "y"
    m[z] = "z"
    return m


def _kernel_symbol_map() -> Dict[Symbol, str]:
    m: Dict[Symbol, str] = {}
    for i in range(3):
        m[sp.Symbol(f"g{i}", real=True)] = f"g[{i}]"
        m[sp.Symbol(f"gd{i}", real=True)] = f"g_dot[{i}]"
        m[sp.Symbol(f"gdd{i}", real=True)] = f"g_ddot[{i}]"
    for i in range(3):
        for j in range(3):
            m[sp.Symbol(f"H{i}{j}", real=True)] = f"H({i},{j})"
            m[sp.Symbol(f"Hd{i}{j}", real=True)] = f"H_dot({i},{j})"
            m[sp.Symbol(f"Hdd{i}{j}", real=True)] = f"H_ddot({i},{j})"
    m[sp.Symbol("eps", real=True, positive=True)] = "eps"
    return m


def _emit_cse_body(
    printer: AlbersPrinter,
    exprs: Sequence[sp.Basic],
    out_names: Sequence[str],
) -> str:
    repls, reduced = sp.cse(list(exprs), optimizations="basic")
    lines: List[str] = []
    for sym, expr in repls:
        lines.append(f"  const real {printer.doprint(sym)} = {printer.doprint(expr)};")
    for name, expr in zip(out_names, reduced):
        lines.append(f"  {name} = {printer.doprint(expr)};")
    return "\n".join(lines)


def emit_quadric_geometry() -> str:
    from quadric import G_expr, H_expr

    printer = AlbersPrinter(_quadric_symbol_map())
    G = G_expr()
    H = H_expr()

    grad = emit_vec3_function(
        "quadric_grad_generated",
        "const vec10 &Q, const vec3 &x",
        [G[0], G[1], G[2]],
        printer,
    )

    hess_lines = ["  mat3 M;", "  M.setZero();"]
    for i in range(3):
        for j in range(3):
            hess_lines.append(f"  M({i},{j}) = {printer.doprint(H[i, j])};")
    hess = f"""
inline mat3 quadric_hessian_generated(const vec10 &Q) {{
{chr(10).join(hess_lines)}
  return M;
}}
"""

    zero = """
inline mat3 quadric_H_directional_generated(const vec10 &, const vec3 &, const vec3 &) {
  return mat3::Zero();
}

inline mat3 quadric_H_directional_rate_generated(const vec10 &, const vec3 &, const vec3 &, const vec3 &) {
  return mat3::Zero();
}
"""
    return grad + hess + zero


def emit_darboux_geometry() -> str:
    from darboux import G_expr, H_expr
    from compose import H_directional, H_directional_rate

    import sympy as sp
    from sympy import Matrix

    fp_sym = Matrix(sp.symbols("fp0:3", real=True))
    fpp_sym = Matrix(sp.symbols("fpp0:3", real=True))
    fp_map = {fp_sym[i]: f"fp[{i}]" for i in range(3)}
    fpp_map = {fpp_sym[i]: f"fpp[{i}]" for i in range(3)}

    printer = AlbersPrinter(_darboux_symbol_map())
    preamble = (
        "  real x = x_v[0], y = x_v[1], z = x_v[2];\n"
        "  real A, B, C, D, E, F, G, H, I, J, lambda, mu, nu, kappa;\n"
        "  unpack_darboux(Q, A, B, C, D, E, F, G, H, I, J, lambda, mu, nu, kappa);\n"
        "  real X = x_v.dot(x_v);\n"
        "  real L = vec3(mu, nu, kappa).dot(x_v);\n"
    )
    G = G_expr()
    grad = emit_vec3_function(
        "darboux_grad_generated",
        "const vec14 &Q, const vec3 &x_v",
        [G[0], G[1], G[2]],
        printer,
        preamble=preamble,
    )

    H = H_expr()
    hess_lines = [
        "  real x = x_v[0], y = x_v[1], z = x_v[2];",
        "  real A, B, C, D, E, F, G, H, I, J, lambda, mu, nu, kappa;",
        "  unpack_darboux(Q, A, B, C, D, E, F, G, H, I, J, lambda, mu, nu, kappa);",
        "  real X = x_v.dot(x_v);",
        "  real L = vec3(mu, nu, kappa).dot(x_v);",
        "  mat3 M = mat3::Zero();",
    ]
    for i in range(3):
        for j in range(i, 3):
            expr = H[i, j]
            if i != j:
                hess_lines.append(f"  M({i},{j}) = M({j},{i}) = {printer.doprint(expr)};")
            else:
                hess_lines.append(f"  M({i},{j}) = {printer.doprint(expr)};")
    hess = "inline mat3 darboux_hessian_generated(const vec14 &Q, const vec3 &x_v) {\n" + "\n".join(
        hess_lines
    ) + "\n  return M;\n}\n"

    H_dir = H_directional(H, fp_sym)
    H_rate = H_directional_rate(H, fp_sym, fpp_sym)

    dir_printer = AlbersPrinter({**_darboux_symbol_map(), **fp_map})
    dir_lines = [
        "  real x = x_v[0], y = x_v[1], z = x_v[2];",
        "  real A, B, C, D, E, F, G, H, I, J, lambda, mu, nu, kappa;",
        "  unpack_darboux(Q, A, B, C, D, E, F, G, H, I, J, lambda, mu, nu, kappa);",
        "  real X = x_v.dot(x_v);",
        "  real L = vec3(mu, nu, kappa).dot(x_v);",
        "  mat3 M = mat3::Zero();",
    ]
    for i in range(3):
        for j in range(3):
            dir_lines.append(f"  M({i},{j}) = {dir_printer.doprint(H_dir[i, j])};")
    h_dir = (
        "inline mat3 darboux_H_directional_generated(const vec14 &Q, const vec3 &x_v, const vec3 &fp) {\n"
        + "\n".join(dir_lines)
        + "\n  return M;\n}\n"
    )

    rate_printer = AlbersPrinter({**_darboux_symbol_map(), **fp_map, **fpp_map})
    rate_lines = dir_lines[:6] + ["  mat3 M = mat3::Zero();"]
    for i in range(3):
        for j in range(3):
            rate_lines.append(f"  M({i},{j}) = {rate_printer.doprint(H_rate[i, j])};")
    h_rate = (
        "inline mat3 darboux_H_directional_rate_generated(const vec14 &Q, const vec3 &x_v, "
        "const vec3 &fp, const vec3 &fpp) {\n"
        + "\n".join(rate_lines)
        + "\n  return M;\n}\n"
    )
    return grad + hess + h_dir + h_rate


def emit_kernels() -> str:
    from compose import compose_energy_abstract

    energy = compose_energy_abstract()
    printer = AlbersPrinter(_kernel_symbol_map())

    shape_op = """
inline void shape_operator_from_GH(const vec3 &g, const mat3 &H, mat3 &W_out) {
  const real s = g.norm();
  if (s < 1e-14) { W_out.setZero(); return; }
  const vec3 n = g / s;
  const mat3 P = mat3::Identity() - n * n.transpose();
  W_out = (P * H * P) / s;
}
"""

    W_dot = energy["W_dot"]
    W_ddot = energy["W_ddot"]
    wdot_exprs = [W_dot[i, j] for i in range(3) for j in range(3)]
    wddot_exprs = [W_ddot[i, j] for i in range(3) for j in range(3)]
    wdot_names = [f"W_dot_out({i},{j})" for i in range(3) for j in range(3)]
    wddot_names = [f"W_ddot_out({i},{j})" for i in range(3) for j in range(3)]

    wdot_body = _emit_cse_body(printer, wdot_exprs, wdot_names)
    wddot_body = _emit_cse_body(printer, wddot_exprs, wddot_names)

    wdot_fn = f"""
inline void shape_operator_dot_from_kinematics(
    const vec3 &g, const mat3 &H, const vec3 &g_dot, const mat3 &H_dot,
    mat3 &W_dot_out) {{
{wdot_body}
}}
"""

    wddot_fn = f"""
inline void shape_operator_ddot_from_kinematics(
    const vec3 &g, const mat3 &H,
    const vec3 &g_dot, const mat3 &H_dot, const vec3 &g_ddot, const mat3 &H_ddot,
    mat3 &W_ddot_out) {{
{wddot_body}
}}
"""

    energy_body = _emit_cse_body(
        printer,
        [energy["E"], energy["E_prime"], energy["E_pprime"]],
        ["E_out", "E_prime_out", "E_pp_out"],
    )

    inv_frob_derivs = f"""
inline void inv_frob_derivs_from_kinematics(
    const vec3 &g, const mat3 &H,
    const vec3 &g_dot, const mat3 &H_dot,
    const vec3 &g_ddot, const mat3 &H_ddot,
    real &E_out, real &E_prime_out, real &E_pp_out,
    real eps) {{
{energy_body}
}}
"""

    kinematics = """
inline void line_kinematics(
    const mat3 &H, const vec3 &fp, const vec3 &fpp,
    const mat3 &H_dot,
    vec3 &g_dot, vec3 &g_ddot) {
  g_dot = H * fp;
  g_ddot = H_dot * fp + H * fpp;
}
"""

    newton = """
inline real newton_step_t(
    real t, real E_prime, real E_pp,
    real min_denom = 1e-14, real lm_lambda = 1e-8, real grad_scale = 0.1) {
  if (std::abs(E_pp) >= min_denom) return t - E_prime / E_pp;
  if (std::abs(E_prime) < 1e-14) return t;
  return t - grad_scale * E_prime;
}
"""

    compose = """
template <typename GeometryBundle, typename LineBundle>
inline void eval_medial_energy_at_t(
    const GeometryBundle &geom, const LineBundle &line, real t,
    real &E, real &E_prime, real &E_pp,
    real eps = 1e-12) {
  const vec3 x = line.f(t);
  const vec3 fp = line.fp(t);
  const vec3 fpp = line.fpp(t);
  const vec3 g = geom.G(x);
  const mat3 H = geom.H(x);
  const mat3 H_dot = geom.H_directional(x, fp);
  const mat3 H_ddot = geom.H_directional_rate(x, fp, fpp);
  vec3 g_dot, g_ddot;
  line_kinematics(H, fp, fpp, H_dot, g_dot, g_ddot);
  inv_frob_derivs_from_kinematics(
      g, H, g_dot, H_dot, g_ddot, H_ddot, E, E_prime, E_pp, eps);
}
"""

    return shape_op + wdot_fn + wddot_fn + inv_frob_derivs + kinematics + newton + compose


def _cyclide_smooth_symbol_map() -> Dict[Symbol, str]:
    m: Dict[Symbol, str] = {}
    for i in range(14):
        m[sp.Symbol(f"Qi{i}", real=True)] = f"Qi[{i}]"
        m[sp.Symbol(f"Qg{i}", real=True)] = f"Q0[{i}]"
        m[sp.Symbol(f"Qj{i}", real=True)] = f"Qj[{i}]"
    for i, comp in enumerate(("x_j_in_i[0]", "x_j_in_i[1]", "x_j_in_i[2]")):
        m[sp.Symbol(f"xj{i}", real=True)] = comp
    m[sp.Symbol("wi", real=True)] = "wi"
    m[sp.Symbol("w_ij", real=True)] = "w_ij"
    m[sp.Symbol("alpha_G", real=True)] = "alpha_G"
    m[sp.Symbol("alpha_H", real=True)] = "alpha_H"
    return m


def _emit_vec14_grad(
    printer: AlbersPrinter,
    grad: Matrix,
    out_name: str = "grad_out",
) -> str:
    names = [f"{out_name}[{k}]" for k in range(grad.rows)]
    return _emit_cse_body(printer, list(grad), names)


def _emit_mat14_assign(printer: AlbersPrinter, mat: Matrix, var_name: str) -> str:
    lines = [f"  {var_name}.setZero();"]
    for i in range(mat.rows):
        for j in range(mat.cols):
            expr = sp.expand(mat[i, j])
            if expr != 0:
                lines.append(
                    f"  {var_name}({i},{j}) = {printer.doprint(expr)};"
                )
    return "\n".join(lines)


def emit_cyclide_smooth() -> str:
    from cyclide_smooth import N_Q, compose_cyclide_smooth

    bundle = compose_cyclide_smooth()
    printer = AlbersPrinter(_cyclide_smooth_symbol_map())

    anchor_e_body = _emit_cse_body(printer, [bundle.E_anchor], ["E_acc"]).replace(
        "E_acc =", "const real E_acc =", 1
    )
    anchor_g_body = _emit_vec14_grad(printer, bundle.grad_anchor)

    neighbor_e_body = _emit_cse_body(printer, [bundle.E_neighbor], ["E_acc"]).replace(
        "E_acc =", "const real E_acc =", 1
    )
    neighbor_g_body = _emit_vec14_grad(printer, bundle.grad_neighbor)

    anchor_h_body = _emit_mat14_assign(printer, bundle.hess_anchor, "H_out")
    neighbor_h_body = _emit_mat14_assign(printer, bundle.hess_neighbor, "H_out")

    anchor_energy = f"""
inline real cyclide_smooth_anchor_energy(
    const vec14 &Qi, const vec14 &Q0, real wi) {{
{anchor_e_body}
  return E_acc;
}}
"""

    anchor_grad = f"""
inline void cyclide_smooth_anchor_grad(
    const vec14 &Qi, const vec14 &Q0, real wi, vec14 &grad_out) {{
{anchor_g_body}
}}
"""

    neighbor_energy = f"""
inline real cyclide_smooth_neighbor_energy(
    const vec14 &Qi, const vec14 &Qj, const vec3 &x_j_in_i,
    real wi, real w_ij, real alpha_G, real alpha_H) {{
{neighbor_e_body}
  return E_acc;
}}
"""

    neighbor_grad = f"""
inline void cyclide_smooth_neighbor_grad(
    const vec14 &Qi, const vec14 &Qj, const vec3 &x_j_in_i,
    real wi, real w_ij, real alpha_G, real alpha_H, vec14 &grad_out) {{
{neighbor_g_body}
}}
"""

    anchor_hess = f"""
inline void cyclide_smooth_anchor_hess(real wi, mat14 &H_out) {{
{anchor_h_body}
}}
"""

    neighbor_hess = f"""
inline void cyclide_smooth_neighbor_hess(
    const vec14 &Qj, const vec3 &x_j_in_i,
    real wi, real w_ij, real alpha_G, real alpha_H, mat14 &H_out) {{
{neighbor_h_body}
}}
"""

    header_comment = f"""
// Cyclide jet-match smooth energy (Phase 1 sympy).
// E_anchor   = wi * ||Qi - Q0||^2
// E_neighbor = (1-wi)*w_ij*(alpha_G*frob(Gi-Gj)^2 + alpha_H*frob(Hi-Hj)^2)
// Gi = G(Qi, x_j_in_i), Gj = G(Qj, 0); Hi/Hj likewise.
// Sum neighbor_energy/grad over one-ring in Phase 2 C++ driver.
"""

    return header_comment + anchor_energy + anchor_grad + neighbor_energy + neighbor_grad + anchor_hess + neighbor_hess


def write_header(path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_banner() + body + _footer())


def emit_all(target: str) -> List[Tuple[str, str]]:
    out: List[Tuple[str, str]] = []
    if target in ("kernels", "all"):
        out.append(("medial_kernels.h", emit_kernels()))
    if target in ("quadric", "all"):
        out.append(("quadric_generated.hpp", emit_quadric_geometry()))
    if target in ("darboux", "all"):
        out.append(("darboux_generated.hpp", emit_darboux_geometry()))
    if target in ("cyclide_smooth", "all"):
        out.append(("cyclide_smooth_generated.hpp", emit_cyclide_smooth()))
    return out
